In [1]:
#!pip install numpy pandas matplotlib seaborn rich scikit-learn

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from rich import print as rprint
%matplotlib inline
sns.set()

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split, KFold, cross_validate
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline

## QM9

#### Loading the data

In [3]:
#preprocessed dataset
qm9_x = pd.read_csv('qm9_features32.csv')
qm9_y = pd.read_csv('qm9_labels.csv')

In [4]:
qm9_x.head()

,"('BalabanJ', <class 'numpy.float64'>)","('BertzCT', <class 'numpy.float64'>)","('Chi0', <class 'numpy.float64'>)","('Chi0n', <class 'numpy.float64'>)","('Chi0v', <class 'numpy.float64'>)","('Chi1', <class 'numpy.float64'>)","('Chi1n', <class 'numpy.float64'>)","('Chi1v', <class 'numpy.float64'>)","('Chi2n', <class 'numpy.float64'>)","('Chi2v', <class 'numpy.float64'>)",...,"('fr_piperdine', <class 'numpy.float64'>)","('fr_piperzine', <class 'numpy.float64'>)","('fr_priamide', <class 'numpy.float64'>)","('fr_pyridine', <class 'numpy.float64'>)","('fr_quatN', <class 'numpy.float64'>)","('fr_term_acetylene', <class 'numpy.float64'>)","('fr_tetrazole', <class 'numpy.float64'>)","('fr_unbrch_alkane', <class 'numpy.float64'>)","('fr_urea', <class 'numpy.float64'>)","('qed', <class 'numpy.float64'>)"
0,0.000020,0.000577,3.875255e-15,2.722966e-11,1.025154e-07,4.102548e-13,1.635214e-11,0.000019,0.000001,2.209078e-07,...,2.388156e-20,0.0,8.336724e-25,0.156951,4.034345e-08,2.957989e-11,0.168378,4.703598e-08,0.166633,0.187493
1,0.000020,0.000577,3.875255e-15,2.722966e-11,1.025154e-07,4.102548e-13,1.635214e-11,0.000019,0.000001,2.209078e-07,...,2.388156e-20,0.0,8.336724e-25,0.156951,4.034345e-08,2.957989e-11,0.168378,4.703598e-08,0.166633,0.228070
2,0.000020,0.000577,3.875255e-15,2.722966e-11,1.025154e-07,4.102548e-13,1.635214e-11,0.000019,0.000001,2.209078e-07,...,2.388156e-20,0.0,8.336724e-25,0.156951,4.034345e-08,2.957989e-11,0.168378,4.703598e-08,0.166633,0.156089
3,0.974937,0.000625,1.574798e-06,2.191668e-09,2.296717e-07,1.101185e-06,1.498512e-07,0.000038,0.000001,2.209078e-07,...,2.388156e-20,0.0,8.336724e-25,0.156951,4.034345e-08,1.000000e+00,0.168378,4.703598e-08,0.166633,0.160976
4,0.974937,0.000646,1.574798e-06,7.501717e-11,1.174156e-07,1.101185e-06,5.282567e-08,0.000033,0.000001,2.209078e-07,...,2.388156e-20,0.0,8.336724e-25,0.156951,4.034345e-08,2.957989e-11,0.168378,4.703598e-08,0.166633,0.197878

In [5]:
qm9_x.describe()

,"('BalabanJ', <class 'numpy.float64'>)","('BertzCT', <class 'numpy.float64'>)","('Chi0', <class 'numpy.float64'>)","('Chi0n', <class 'numpy.float64'>)","('Chi0v', <class 'numpy.float64'>)","('Chi1', <class 'numpy.float64'>)","('Chi1n', <class 'numpy.float64'>)","('Chi1v', <class 'numpy.float64'>)","('Chi2n', <class 'numpy.float64'>)","('Chi2v', <class 'numpy.float64'>)",...,"('fr_piperdine', <class 'numpy.float64'>)","('fr_piperzine', <class 'numpy.float64'>)","('fr_priamide', <class 'numpy.float64'>)","('fr_pyridine', <class 'numpy.float64'>)","('fr_quatN', <class 'numpy.float64'>)","('fr_term_acetylene', <class 'numpy.float64'>)","('fr_tetrazole', <class 'numpy.float64'>)","('fr_unbrch_alkane', <class 'numpy.float64'>)","('fr_urea', <class 'numpy.float64'>)","('qed', <class 'numpy.float64'>)"
count,133885.000000,133885.000000,1.338850e+05,1.338850e+05,1.338850e+05,1.338850e+05,1.338850e+05,133885.000000,133885.000000,1.338850e+05,...,1.338850e+05,133885.000000,1.338850e+05,133885.000000,1.338850e+05,1.338850e+05,133885.000000,1.338850e+05,133885.000000,133885.000000
mean,0.861224,0.006409,1.521402e-03,2.452571e-03,1.548950e-03,1.917757e-03,5.469812e-03,0.003792,0.020456,1.119351e-02,...,6.518926e-02,0.005768,2.293760e-02,0.163808,9.149683e-03,1.011540e-01,0.170559,1.463843e-02,0.173879,0.317016
std,0.108996,0.003880,6.312036e-04,1.552160e-03,9.756258e-04,4.813187e-04,4.169740e-03,0.002516,0.025184,1.503937e-02,...,2.468584e-01,0.073852,1.497051e-01,0.075721,9.521552e-02,3.015336e-01,0.042525,1.185325e-01,0.077366,0.092110
min,0.000020,0.000577,3.875255e-15,2.722966e-11,1.025154e-07,4.102548e-13,1.635214e-11,0.000019,0.000001,2.209078e-07,...,2.388156e-20,0.000000,8.336724e-25,0.156951,4.034345e-08,2.957989e-11,0.168378,4.703598e-08,0.166633,0.023618
25%,0.790194,0.003778,1.039987e-03,1.400653e-03,8.926134e-04,1.781174e-03,2.274259e-03,0.001880,0.003210,1.428882e-03,...,2.388156e-20,0.000000,8.336724e-25,0.156951,4.034345e-08,2.957989e-11,0.168378,4.703598e-08,0.166633,0.262702
50%,0.878187,0.005487,1.468291e-03,2.108546e-03,1.329561e-03,2.040303e-03,4.446247e-03,0.003213,0.011170,5.500636e-03,...,2.388156e-20,0.000000,8.336724e-25,0.156951,4.034345e-08,2.957989e-11,0.168378,4.703598e-08,0.166633,0.319758
75%,0.955749,0.007919,2.033744e-03,3.127838e-03,1.963294e-03,2.242159e-03,7.634490e-03,0.005111,0.027772,1.472785e-02,...,2.388156e-20,0.000000,8.336724e-25,0.156951,4.034345e-08,2.957989e-11,0.168378,4.703598e-08,0.166633,0.378115
max,0.998183,0.036156,4.048517e-03,1.951057e-02,1.279171e-02,2.706603e-03,2.709209e-02,0.016903,0.233448,1.552554e-01,...,1.000000e+00,0.984491,1.000000e+00,0.999979,1.000000e+00,1.000000e+00,1.000000,9.999997e-01,1.000000,0.619620

In [6]:
qm9_y.head()

,mu,alpha,homo,lumo,gap,r2,zpve,cv,u0,u298,h298,g298
0,0.0000,13.21,-0.3877,0.1171,0.5048,35.3641,0.044749,6.469,-40.478930,-40.476062,-40.475117,-40.498597
1,1.6256,9.46,-0.2570,0.0829,0.3399,26.1563,0.034358,6.316,-56.525887,-56.523026,-56.522082,-56.544961
2,1.8511,6.31,-0.2928,0.0687,0.3615,19.0002,0.021375,6.002,-76.404702,-76.401867,-76.400922,-76.422349
3,0.0000,16.28,-0.2845,0.0506,0.3351,59.5248,0.026841,8.574,-77.308427,-77.305527,-77.304583,-77.327429
4,2.8937,12.99,-0.3604,0.0191,0.3796,48.7476,0.016601,6.278,-93.411888,-93.409370,-93.408425,-93.431246

In [7]:
qm9_y.describe()

,mu,alpha,homo,lumo,gap,r2,zpve,cv,u0,u298,h298,g298
count,133885.000000,133885.000000,133885.000000,133885.000000,133885.000000,133885.000000,133885.000000,133885.000000,133885.000000,133885.000000,133885.000000,133885.000000
mean,2.706037,75.191296,-0.239977,0.011124,0.251100,1189.527450,0.148524,31.600676,-411.543985,-411.535513,-411.534569,-411.577397
std,1.530394,8.187793,0.022131,0.046936,0.047519,279.757172,0.033274,4.062471,40.060230,40.060012,40.060012,40.060741
min,0.000000,6.310000,-0.428600,-0.175000,0.024600,19.000200,0.015951,6.002000,-714.568061,-714.560153,-714.559209,-714.602138
25%,1.588700,70.380000,-0.252500,-0.023800,0.216300,1018.322600,0.125289,28.942000,-437.913936,-437.905942,-437.904997,-437.947682
50%,2.500000,75.500000,-0.241000,0.012000,0.249400,1147.585800,0.148329,31.555000,-417.864758,-417.857351,-417.856407,-417.895731
75%,3.636100,80.520000,-0.228700,0.049200,0.288200,1308.816600,0.171150,34.276000,-387.049166,-387.039746,-387.038802,-387.083279
max,29.556400,196.620000,-0.101700,0.193500,0.622100,3374.753200,0.273944,46.969000,-40.478930,-40.476062,-40.475117,-40.498597

In [8]:
rprint(qm9_x.shape, qm9_y.shape)

(133885, 163)
(133885, 12)

## Linear Regression with one task

In [9]:
res = []
X = qm9_x.to_numpy()
for task_name in qm9_y.columns:
    model = LinearRegression()
    y = qm9_y[task_name].to_numpy().flatten()
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
    scaler = StandardScaler().fit(X_train)
    model.fit(scaler.transform(X_train), y_train)
    y_pred = model.predict(scaler.transform(X_test))
    r2 = r2_score(y_test, y_pred)
    mse = mean_squared_error(y_test, y_pred)
    mae = mean_absolute_error(y_test, y_pred)
    res.append({'task':task_name, 'r2 score':r2, 'mean squared error':mse, 'mean absoulute error':mae})
rprint('[red]Linear Regression results on each task')
pd.DataFrame.from_dict(res)

Linear Regression results on each task

     task      r2 score  mean squared error  mean absoulute error
0      mu -5.260487e+13        1.215235e+14          67368.044000
1   alpha -5.194533e+01        3.561504e+03              1.509017
2    homo  7.555959e-01        1.209700e-04              0.008181
3    lumo -6.706484e+11        1.477817e+09            234.937083
4     gap  8.418631e-01        3.631725e-04              0.014249
5      r2 -2.153413e+02        1.669011e+07             92.340353
6    zpve -1.632371e+01        1.903901e-02              0.002436
7      cv  9.758500e-01        3.978320e-01              0.457351
8      u0  9.942731e-01        9.136283e+00              1.946199
9    u298 -4.787317e+00        9.175459e+03              2.509163
10   h298 -1.047686e+11        1.701508e+14          79716.220535
11   g298  9.937737e-01        9.998513e+00              1.932131

### Cross Validation

In [10]:
res = []
X = qm9_x.to_numpy()
for task_name in qm9_y.columns:
    y = qm9_y[task_name].to_numpy().flatten()
    r2 = []
    mse = []
    mae = []
    kfold = KFold(n_splits=5)
    for (train_indx, test_indx) in kfold.split(X, y):
        X_train, y_train = X[train_indx], y[train_indx]
        X_test, y_test = X[test_indx], y[test_indx]
        scaler = StandardScaler().fit(X_train)
        model = LinearRegression()
        model.fit(scaler.transform(X_train), y_train)
        y_pred = model.predict(scaler.transform(X_test))
        r2 .append( r2_score(y_test, y_pred))
        mse.append( mean_squared_error(y_test, y_pred))
        mae.append( mean_absolute_error(y_test, y_pred))
    d = dict()
    d['task'] = task_name
    for i in range(len(r2)):
        d[f'r2_k{i+1}'] = r2[i]
        d[f'mse_k{i+1}'] = mse[i]
        d[f'mae_k{i+1}'] = mae[i]
    d['r2_mean'] = np.mean(r2)
    d['mse_mean'] = np.mean(mse)
    d['mae_mean'] = np.mean(mae)
    res.append(d)
rprint('[red]Linear regression cross validation on each task')
df = pd.DataFrame.from_dict(res)
df

Linear regression cross validation on each task

,task,r2_k1,mse_k1,mae_k1,r2_k2,mse_k2,mae_k2,r2_k3,mse_k3,mae_k3,r2_k4,mse_k4,mae_k4,r2_k5,mse_k5,mae_k5,r2_mean,mse_mean,mae_mean
0,mu,-6.425881e+19,1.474327e+20,3.152497e+09,-966.779463,2.249699e+03,1.112087,0.565380,1.017123,0.712208,0.559085,0.960651,0.669843,-2.782791e+13,7.010968e+13,5.117003e+04,-1.285177e+19,2.948656e+19,6.305095e+08
1,alpha,-1.013108e+18,7.955314e+19,2.315721e+09,-26.025632,1.150466e+03,1.584560,0.947346,2.218978,1.047159,0.951026,2.022652,0.970317,-1.541361e+16,9.554115e+17,5.973301e+06,-2.057044e+17,1.610171e+19,4.643389e+08
2,homo,-5.227614e+19,3.231676e+16,4.667363e+07,-898.855505,6.165003e-01,0.013439,0.662199,0.000114,0.008006,0.627837,0.000105,0.007680,-3.665636e+15,1.780616e+12,8.154637e+03,-1.045596e+19,6.463709e+15,9.336357e+06
3,lumo,-2.290949e+18,5.371873e+15,1.902920e+07,-168.157079,3.273793e-01,0.017092,0.869886,0.000253,0.012103,0.897461,0.000194,0.010700,-1.086116e+17,2.911521e+14,1.042747e+05,-4.799121e+17,1.132605e+15,3.826695e+06
4,gap,-4.546998e+18,1.121265e+16,2.749235e+07,-971.213743,1.845959e+00,0.023729,0.805337,0.000368,0.014484,0.847176,0.000290,0.012982,-1.250775e+17,3.386953e+14,1.124666e+05,-9.344151e+17,2.310270e+15,5.520963e+06
5,r2,-2.818913e+17,1.795835e+22,3.479292e+10,-387.048022,2.270370e+07,102.157198,0.879464,6728.744377,60.241860,0.824738,9557.562955,74.380238,-4.536556e+16,4.242733e+21,3.980540e+08,-6.545138e+16,4.440217e+21,7.038195e+09
6,zpve,-1.484611e+17,1.522558e+14,3.203647e+06,-29.044499,1.905166e-02,0.002629,0.995609,0.000003,0.001430,0.995286,0.000003,0.001455,-4.122230e+16,6.681686e+13,4.995306e+04,-3.793669e+16,4.381454e+13,6.507200e+05
7,cv,-1.116845e+18,1.903764e+19,1.132829e+09,-17.496738,1.322573e+02,0.591431,0.961933,0.371461,0.464722,0.963682,0.334652,0.438102,-2.661596e+14,4.520072e+15,4.108585e+05,-2.234222e+17,3.808432e+18,2.266479e+08
8,u0,-4.097245e+16,8.306291e+19,2.366253e+09,-18.262518,1.867074e+04,2.805732,0.994606,5.269724,1.711541,0.995274,4.543576,1.664865,-6.712016e+16,9.167284e+19,5.851126e+07,-2.161852e+16,3.494715e+19,4.849529e+08
9,u298,-4.098586e+16,8.308907e+19,2.366626e+09,-18.261292,1.866947e+04,2.805718,0.994600,5.274994,1.712572,0.995274,4.543459,1.664851,-6.711900e+16,9.167291e+19,5.851128e+07,-2.162097e+16,3.495239e+19,4.850274e+08
10,h298,-4.098587e+16,8.308907e+19,2.366626e+09,-18.261294,1.866948e+04,2.805718,0.994602,5.273180,1.712254,0.995275,4.543281,1.664836,-6.711900e+16,9.167290e+19,5.851127e+07,-2.162097e+16,3.495240e+19,4.850274e+08
11,g298,-4.093815e+16,8.299568e+19,2.365295e+09,-18.268942,1.867723e+04,2.805901,0.994601,5.274194,1.712302,0.995274,4.543688,1.664932,-6.712466e+16,9.167777e+19,5.851283e+07,-2.161256e+16,3.493469e+19,4.847616e+08

## Multiple Linear Regression

In [11]:
model = LinearRegression()
X = qm9_x.to_numpy()
y = qm9_y.to_numpy()
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1)
scaler = StandardScaler().fit(X_train)
model.fit(scaler.transform(X_train), y_train)
y_pred = model.predict(scaler.transform(X_test))
r2 = r2_score(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
rprint('[red]Multiple Linear Regression result')
rprint(f'r2_score = {r2}\nmean squared error = {mse}\nmean absolute error = {mae}')

Multiple Linear Regression result

r2_score = 0.8984810175813798
means squared error = 746.0786980638585
mean absolute error = 6.544925759628847

### Cross Validation

In [12]:
pipeline = make_pipeline(StandardScaler(), LinearRegression())
kfold = KFold(n_splits=8, shuffle=True)
scores = cross_validate(pipeline, X, y, cv=kfold, scoring=['r2', 'neg_mean_squared_error', 'neg_mean_absolute_error'], return_train_score=True)

In [13]:
rprint("[red]Multiple linear regression cross validation results")
pd.DataFrame.from_dict(scores)

Multiple linear regression cross validation results

,fit_time,score_time,test_r2,train_r2,test_neg_mean_squared_error,train_neg_mean_squared_error,test_neg_mean_absolute_error,train_neg_mean_absolute_error
0,1.979758,0.034517,9.013867e-01,0.899303,-7.233239e+02,-722.702384,-6.466942e+00,-6.479389
1,1.938343,0.033758,8.986645e-01,0.899685,-7.288115e+02,-721.904268,-6.490017e+00,-6.455474
2,1.954027,0.033419,9.017515e-01,0.899255,-7.063574e+02,-725.127970,-6.482020e+00,-6.473415
3,1.973312,0.058525,8.964531e-01,0.899993,-7.254411e+02,-722.473423,-6.489589e+00,-6.466562
4,2.360203,0.040982,-6.494034e+14,0.899591,-6.689642e+17,-722.719626,-4.032674e+06,-6.476168
5,1.985952,0.055224,8.986830e-01,0.899681,-7.302573e+02,-721.755753,-6.492006e+00,-6.480022
6,1.926745,0.033338,8.981253e-01,0.899749,-7.346034e+02,-721.219868,-6.521203e+00,-6.474304
7,2.041031,0.067007,8.987392e-01,0.899431,-7.303930e+02,-722.564807,-6.462603e+00,-6.476985